spring:
  application:
    name: micro-service-consumer-movie-feign
server:
  port: 7901
eureka:
  client:
    serviceUrl:
      defaultZone: http://yuanjie:123456@localhost:8761/eureka
  instance:
    prefer-ip-address: true